services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: teacher
      POSTGRES_PASSWORD: teacher
      POSTGRES_DB: teacher
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
